name: build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: /home/deployer/copyHistory.sh
      - run: cd server
      - run: npm i
      - run: cd ../client
      - run: npm i
      - run: npm run build
      - run: /home/deployer/pasteHistory.sh
      - run: pm2 stop 0
      - run: pm2 start 0
      - run: pm2 save
      - run: sudo service nginx restart
          
